### ISSUE TITLE
non-ssl fails

### ISSUE THREAD

**Issue by brettswift** [camptocamp/puppet-ghostbuster#14]
Great to see this module :)   

I'd love a flag to use a non-ssl integration with PuppetDB.   I'm not sure I'll have any time soon to send a PR for this, but would love to see it!

**Comment by mcanevet** [comment]
@brettswift I'm not sure to understand.
If you don't want ssl why don't you juste use?

``` shell
$ puppet-ghostbuster -s http://puppetdb:8080
```

**Comment by mcanevet** [comment]
@brettswift puppet-ghostbuster works without connecting to the puppetdb in SSL. If it's not what you want, feel free to reopen.
