### ISSUE TITLE
PuppetDB 3+ support

### ISSUE THREAD

**Issue by daenney** [camptocamp/puppet-ghostbuster#15]
With PuppetDB 3 and later the v2/v3 API endpoints have been retired. The puppetdb-ruby client this depends on does not support the v4 API without some minor patching but the project seems dead.

Essentially the patch I did locally was:

```
    PuppetDB::Client.new({
      :server => configuration.puppetdbserverurl,
      :pem    => {
        'key'     => configuration.hostprivkey,
        'cert'    => configuration.hostcert,
        'ca_file' => configuration.localcacert,
      }
    }, 4)
```

(notice the `, 4` thing before the closing `)`)

And then calling it with `-s https://my-puppetdb-host:8081/pdb/query` appears to do the trick.

**Comment by mcanevet** [comment]
@daenney could you provide a PR? I'll merge it ASAP!

**Comment by daenney** [comment]
@mcanevet What would you like the PR to look like? I can patch that `, 4` thing in there but I'm guessing we'd like this to be settable by the end user and automatically add the `/pdb/query` path in that case?

**Comment by mcanevet** [comment]
@daenney honestly I didn't know that someone else than us is using this piece of code :-) I think we can get rid of puppetdb < 3 and support only API v4

**Comment by daenney** [comment]
Alright, that simplifies things. I'll whip something up.

**Comment by daenney** [comment]
That PR should do it, do test it though 😄. I might be missing some other local modification I made but I believe that's all it takes.
