### ISSUE TITLE
Transfer to Vox Pupuli?

### ISSUE THREAD

**Issue by JoshuaSmeda** [camptocamp/puppet-ghostbuster#66]
Hi Camp2Camp,

Would there be any interest in transferring this repository to Vox Pupuli?

With @raphink moving on, the community might worry that the project will descend further into obsoleteness. Vox Pupuli has expressed interest, and requested that I lodge this issue to determine if you would be willing to migrate?

**Comment by raphink** [comment]
Maybe talk to @saimonn about this :-)

**Comment by mcanevet** [comment]
@raphink ah! we forgot that one when we transferred a bunch of projects to Vox Pupuli. :-)

**Comment by raphink** [comment]
I think I had suggested it, but it wasn't a priority for the community iirc

**Comment by saimonn** [comment]
Hey :wave:, thanks all folks for reminding this, 
@bastelfreak do you have an opinion on this ?

**Comment by bastelfreak** [comment]
Hi,
yes. please migrate it. let me know if anybody from camptocamp wants to keep merge permissions and I can configure that afterwards.

**Comment by saimonn** [comment]
Hi all, I've just transferred this repository to voxpupuli, thanks for your patience.
~I'll close this issue.~
edit: I can't close this issue as I'm not the owner anymore, I'll let voxpupuli members do it.

**Comment by ekohl** [comment]
@raphink @mcanevet @saimonn looks like the gem wasn't done (see owners at https://rubygems.org/gems/puppet-ghostbuster) so release failed: https://github.com/voxpupuli/puppet-ghostbuster/actions/runs/6833930699/job/18587131692

Could one of you please add the PMC? The command is in the failed action.

**Comment by zilchms** [comment]
new years ping for @raphink @mcanevet and @saimonn . anyone of you still in the position to help with this? :)

**Comment by mcanevet** [comment]
@ekohl @zilchms what Email / Handle should I add?

**Comment by bastelfreak** [comment]
Please add pmc@voxpupuli.org

**Comment by mcanevet** [comment]
should be OK now

**Comment by bastelfreak** [comment]
> You were added as an owner to puppet-ghostbuster gem

Thanks!
