### ISSUE TITLE
Release 1.2.0 broken by hiera datadir support

### ISSUE THREAD

**Issue by zilchms** [camptocamp/puppet-ghostbuster#89]
Seems we have accidentally broken something by trying to support hiera datadir. See #86 
@bastelfreak @alexjfisher @h0tw1r3 
Tagging you here to keep this all in one place and keep track.

**Comment by h0tw1r3** [comment]
I have more branches in the queue to modernize how ghostbuster works. Unfortunately it's very opinionated about the path names it processes (ie. *must* be prefixed with `./), and the various tests can parse the filenames in different ways (classes for sure are different).

@alexjfisher it's not immediately apparent from the output why this is happening.

Can you provide the full command you're running, and the general directory layout of the thing being ghost busted?

**Comment by alexjfisher** [comment]
It's the puppet-lint plugin that's broken if you don't have `HIERA_YAML_PATH` set and the default `/etc/puppetlabs/code/hiera.yaml` doesn't exist either.
I wasn't explicitly trying to do anything with puppet-ghostbuster, (but it is in my control-repo Gemfile, so my puppet-lint jobs started to fail).  I guess previously, the `check` method returned early [here](https://github.com/voxpupuli/puppet-ghostbuster/pull/86/files#diff-e588fd982042106290afcb0310352c8ae34a65da323ea9324530ae13df8e1912L31).

**Comment by alexjfisher** [comment]
@h0tw1r3 I've opened a one line PR on a random module to demonstrate https://github.com/voxpupuli/puppet-extlib/pull/219
